#!/usr/bin/env bash
cleanup() {
    rm -rf CornerUnrounder* 2>/dev/null
}

while [[ $# -ge 1 ]]; do
    case $1 in
        -clean)
            cleanup
            exit;;
        *)
            echo "Invalid command."
            exit
    esac
    shift
done
cleanup
aapt package -M AndroidManifest.xml -S res/ -I ~/Android/Sdk/platforms/android-28/android.jar -F CornerUnrounder.apk.u
jarsigner -keystore ~/keystores/shagbag913.jks CornerUnrounder.apk.u shagbag913
zipalign 4 CornerUnrounder.apk.u CornerUnrounder.apk
mkdir -p magisk-module/system/product/overlay
cp CornerUnrounder.apk magisk-module/system/product/overlay/
cd magisk-module && zip -r9 ../CornerUnrounder.zip *
