#!/usr/bin/env bash
cleanup() {
    rm -rf ShagFontage* 2>/dev/null
}

while [[ $# -ge 1 ]]; do
    case $1 in
        -clean)
            cleanup
            exit;;
        *)
            echo "Invalid command."
            exit
    esac
    shift
done
cleanup
aapt package -M AndroidManifest.xml -S res/ -I ~/Android/Sdk/platforms/android-28/android.jar -F ShagFontage.apk.u
jarsigner -keystore ~/keystores/shagbag913.jks ShagFontage.apk.u shagbag913
zipalign 4 ShagFontage.apk.u ShagFontage.apk
